### ISSUE TITLE
Recognize the contributions of members?

### ISSUE THREAD

**Issue by andyyPark** [QC-UCI/qc-uci.club#27] opened 2020-09-26 20:33 UTC
Although this project is relatively simple, I was thinking of adding a section in our REAEDME to recognize all the contributors. Here is an idea: [https://github.com/all-contributors/all-contributors](url)

**Comment by omarcostahamido** [comment] 2020-09-26 21:10
duplicate of #22 right?

also the url. somehow is hyperlinked to https://github.com/QC-UCI/QC-UCI.github.io/issues/url

**Comment by andyyPark** [comment] 2020-09-26 21:22
Oops you are right let me close this one

**Closed as completed** 2020-09-26 21:23 UTC
Labels: documentation, question, LOW

**Comment by omarcostahamido** [comment] 2020-09-26 21:28
if anything this means that we are thinking alike. 
which is a good sign!
